version: "3.9"

services:
  backend:
    build: ./backend
    container_name: wordgame-backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: wordgame-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
